// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mcp_decompose_mass
Rcpp::List mcp_decompose_mass(double mass, double abs_error, Rcpp::NumericVector mono_masses, Rcpp::CharacterVector element_names, Rcpp::IntegerVector min_counts, Rcpp::IntegerVector max_counts);
RcppExport SEXP _MSCC_mcp_decompose_mass(SEXP massSEXP, SEXP abs_errorSEXP, SEXP mono_massesSEXP, SEXP element_namesSEXP, SEXP min_countsSEXP, SEXP max_countsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mass(massSEXP);
    Rcpp::traits::input_parameter< double >::type abs_error(abs_errorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mono_masses(mono_massesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type element_names(element_namesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type min_counts(min_countsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type max_counts(max_countsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcp_decompose_mass(mass, abs_error, mono_masses, element_names, min_counts, max_counts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSCC_mcp_decompose_mass", (DL_FUNC) &_MSCC_mcp_decompose_mass, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSCC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
