# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcp_decompose_mass <- function(mass, abs_error, mono_masses, element_names, min_counts, max_counts) {
    .Call(`_MSCC_mcp_decompose_mass`, mass, abs_error, mono_masses, element_names, min_counts, max_counts)
}

